drop table if exists film_genres;
drop table if exists film_likes;
drop table if exists friendships;
drop table if exists films;
drop table if exists users;
drop table if exists genres;
drop table if exists rating;


create table if not exists rating (
    id integer generated by default as identity primary key ,
    name varchar(100),
    description varchar(150)
);

create table if not exists genres (
    id int auto_increment primary key,
    name varchar(100)
);

create table  if not exists users (
    id int auto_increment primary key,
    email varchar(255) not null,
    login varchar(100) not null,
    name varchar(255),
    birthday date not null
);

create table  if not exists films (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(200),
    release_date date,
    duration int check (duration > 0),
    rating_id int,
    foreign key (rating_id) references rating(id)
);

create table if not exists film_genres (
    genre_id int not null,
    film_id int not null,
    primary key (film_id, genre_id),
    foreign key (film_id) references films(id),
    foreign key (genre_id) references genres(id)
);

create table if not exists film_likes (
    film_id int not null,
    user_id int not null,
    primary key (film_id, user_id),
    foreign key (film_id) references films(id),
    foreign key (user_id) references users(id)
);

create table if not exists friendships (
    user_id int not null,
    friend_id int not null,
    confirmed boolean default false,
    primary key (user_id, friend_id),
    foreign key (user_id) references users(id),
    foreign key (friend_id) references users(id)
);

insert into rating (id, name, description) values
    (1, 'G', 'Все возрастные группы допущены. Материал подходит для детей.'),
    (2, 'PG', 'Рекомендуется просмотр с родителями. Некоторые материалы могут не подойти для детей.'),
    (3, 'PG-13', 'Настоятельное предостережение родителям. Некоторые материалы могут быть не подходят для детей до 13 лет.'),
    (4, 'R', 'Лица, не достигшие 17 лет, допускаются на фильм только в сопровождении одного из родителей или законного представителя.'),
    (5, 'NC-17', 'Лица 17 лет и младше на фильм не допускаются. Это строго взрослый рейтинг.');

insert into genres (id, name) values
    (1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Боевик'),
    (4, 'Триллер'),
    (5, 'Ужасы'),
    (6, 'Фантастика'),
    (7, 'Фэнтези'),
    (8, 'Мелодрама'),
    (9, 'Детектив'),
    (10, 'Приключения');

insert into users (email, login, name, birthday) values
    ('admintema.leshkin@gmail.com', 'temlesk', 'Tema', '2005-05-14'),
    ('usertema.leshkingmail.com', 'userTema', 'Meme', '2000-01-01');

insert into films (name, description, release_date, duration, rating_id) values
    ('Terminator', 'XZ', '2005-05-14', 60, 3),
    ('Java', 'db', '2025-04-22', 120, 1);

insert into film_genres (film_id, genre_id) values
    (1, 2), (1, 3),
    (2, 4), (2, 5);