create table if not exists rating (
    id integer generated by default as identity primary key ,
    name varchar(100),
    description varchar(150)
);

create table if not exists genres (
    id int auto_increment primary key,
    name varchar(100)
);

create table  if not exists users (
    id int auto_increment primary key,
    email varchar(255) not null,
    login varchar(100) not null,
    name varchar(255),
    birthday date not null
);

create table  if not exists films (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(200),
    release_date date,
    duration int check (duration > 0),
    rating_id int,
    foreign key (rating_id) references rating(id)
);

create table if not exists film_genres (
    genre_id int not null,
    film_id int not null,
    primary key (film_id, genre_id),
    foreign key (film_id) references films(id),
    foreign key (genre_id) references genres(id)
);

create table if not exists film_likes (
    film_id int not null,
    user_id int not null,
    primary key (film_id, user_id),
    foreign key (film_id) references films(id),
    foreign key (user_id) references users(id)
);

create table if not exists friendships (
    user_id int not null,
    friend_id int not null,
    confirmed boolean default false,
    primary key (user_id, friend_id),
    foreign key (user_id) references users(id),
    foreign key (friend_id) references users(id)
);